site_name: pyquil-for-azure-quantum
site_url: https://rigetti.github.io/pyquil-for-azure-quantum/
nav:
  - Home: index.md
  - API Reference: api_reference.md

plugins:
  - include-markdown
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material

watch:
  - README.md
  - pyquil_for_azure_quantum
